# -*- coding: utf-8 -*-
"""Online_Retail.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRLgnKYAORN1FBV0SS1MEvBnhO--HHWB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier

import pickle

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Machine_Learning/online_retail.csv')
df.head()

df.info()
df.describe()

df.describe(include='all')

plt.figure()
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Matrix")
plt.show()

sns.regplot(x='Quantity', y='UnitPrice', data=df)
plt.title("Regression Line")
plt.show()

sns.histplot(df['Quantity'], bins=50)
plt.title("Quantity Distribution")
plt.show()

sns.countplot(x='Country', data=df)
plt.xticks(rotation=90)
plt.show()

df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

df['TotalPrice'] = df['Quantity'] * df['UnitPrice']
df['HighValue'] = df['TotalPrice'].apply(lambda x: 1 if x > 100 else 0)

le = LabelEncoder()
df['Country'] = le.fit_transform(df['Country'])

scaler = StandardScaler()

X = df[['Quantity','UnitPrice','Country']]
y = df['HighValue']

X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

models = {
    "Logistic Regression": LogisticRegression(),
    "SVM": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "AdaBoost": AdaBoostClassifier()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(name, "Accuracy:", accuracy_score(y_test, pred))



from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

X = df[['Quantity', 'UnitPrice', 'Country']]
y = df['HighValue']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

clf.fit(X_train_scaled, y_train)

# Define classifiers
classifiers = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SVM": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "AdaBoost": AdaBoostClassifier()
}

# Train each classifier and collect results
results = []

for name, clf in classifiers.items():

    # Train model
    clf.fit(X_train_scaled, y_train)

    # Predict
    y_pred = clf.predict(X_test_scaled)

    # Metrics (safe for binary + multiclass)
    acc       = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall    = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1        = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    # Store results
    results.append({
        'Model'     : name,
        'Accuracy'  : round(acc, 4),
        'Precision' : round(precision, 4),
        'Recall'    : round(recall, 4),
        'F1 Score'  : round(f1, 4)
    })

    print(f'{name:22s} -> Accuracy: {acc:.4f} | F1: {f1:.4f}')

# Convert to DataFrame
results_df = pd.DataFrame(results)

# Sort by Accuracy
results_df = results_df.sort_values(by='Accuracy', ascending=False)

# Reset index for ranking
results_df = results_df.reset_index(drop=True)
results_df.index += 1

print('\n✅ All models trained!\n')
print(results_df)

import matplotlib.pyplot as plt

results_df.set_index("Model")[["Accuracy", "F1 Score"]].plot(kind="bar")
plt.title("Model Comparison")
plt.ylabel("Score")
plt.xticks(rotation=45)
plt.show()

best_model_name = results_df.iloc[0]["Model"]
print("Best Model:", best_model_name)

metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
models = results_df['Model'].tolist()

# Colors (one for each subplot)
colors = ['#3498db', '#e67e22', '#2ecc71', '#9b59b6']

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for i, (metric, color) in enumerate(zip(metrics, colors)):

    values = results_df[metric].tolist()

    bars = axes[i].barh(models, values, color=color, alpha=0.85, edgecolor='black')

    # Add value labels
    for bar, val in zip(bars, values):
        axes[i].text(val + 0.001,
                     bar.get_y() + bar.get_height()/2,
                     f'{val:.3f}',
                     va='center', ha='left',
                     fontsize=9, fontweight='bold')

    axes[i].set_title(metric, fontsize=13, fontweight='bold')
    axes[i].set_xlim(0, 1.05)   # safer than 0.85–1.02
    axes[i].set_xlabel('Score')

plt.suptitle('Model Performance Comparison', fontsize=16, fontweight='bold')
plt.tight_layout()
plt.show()

results_df = results_df.sort_values(by="Accuracy", ascending=True)

metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
titles  = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
colors  = ['#5DADE2', '#EB984E', '#58D68D', '#AF7AC5']

models = results_df['Model'].tolist()

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

for i, metric in enumerate(metrics):

    values = results_df[metric].tolist()

    bars = axes[i].barh(models, values,
                        color=colors[i],
                        edgecolor='black',
                        alpha=0.9)

    # Add labels inside bars (like your image)
    for bar, val in zip(bars, values):
        axes[i].text(val - 0.01,
                     bar.get_y() + bar.get_height()/2,
                     f'{val:.4f}',
                     va='center', ha='right',
                     color='white', fontsize=9, fontweight='bold')

    axes[i].set_title(titles[i], fontsize=13, fontweight='bold')
    axes[i].set_xlim(0.85, 1.02)   # match your style
    axes[i].set_xlabel('Score')

# Main title
plt.suptitle('Model Performance Comparison', fontsize=16, fontweight='bold', y=1.02)

plt.tight_layout()
plt.show()

results_df.style\
    .background_gradient(subset=['Accuracy', 'Precision', 'Recall', 'F1 Score'],
                         cmap='YlGn')\
    .set_caption('📊 Model Comparison — sorted by Accuracy')\
    .format({'Accuracy': '{:.4f}', 'Precision': '{:.4f}',
             'Recall': '{:.4f}', 'F1 Score': '{:.4f}'})

x      = np.arange(len(models))
width  = 0.2
colors = ['#3498db', '#e67e22', '#2ecc71', '#9b59b6']

fig, ax = plt.subplots(figsize=(14, 6))

for i, (metric, color) in enumerate(zip(metrics, colors)):
    offset = (i - 1.5) * width
    ax.bar(x + offset, results_df[metric], width, label=metric,
           color=color, alpha=0.85, edgecolor='black')

ax.set_xticks(x)
ax.set_xticklabels(models, rotation=15, ha='right', fontsize=10)
ax.set_ylim(0.85, 1.05)
ax.set_ylabel('Score')
ax.set_title('All Metrics Side by Side', fontsize=14, fontweight='bold')
ax.legend(loc='lower right')
ax.axhline(y=1.0, color='grey', linestyle='--', linewidth=0.8)

plt.tight_layout()
plt.show()

from sklearn.metrics import confusion_matrix

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

for i, (name, clf) in enumerate(classifiers.items()):
    # Get predictions
    y_pred = clf.predict(X_test_scaled)

    # Compute confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Plot heatmap
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Malignant', 'Benign'],
                yticklabels=['Malignant', 'Benign'],
                ax=axes[i], linewidths=1)

    acc = accuracy_score(y_test, y_pred)
    axes[i].set_title(f'{name}\nAccuracy: {acc:.4f}', fontweight='bold')
    axes[i].set_xlabel('Predicted')
    axes[i].set_ylabel('Actual')

plt.suptitle('Confusion Matrices — All Models', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import joblib

# Create pipeline
lr_pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

import joblib
from sklearn.metrics import r2_score

# 1. Fit and Predict using only the Linear Regression pipeline
lr_pipeline.fit(X_train, y_train)
preds = lr_pipeline.predict(X_test)

# 2. Evaluate performance
score = r2_score(y_test, preds)

# 3. Save the model to a file
joblib.dump(lr_pipeline, 'linear_regression_model.pkl')

print("Linear Regression Analysis Complete")
print("-" * 30)
print(f"R² Score: {score:.4f}")
print("Model saved to: linear_regression_model.pkl")

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', RandomForestClassifier())
])

pipeline.fit(X_train, y_train)

joblib.dump(pipeline, "model.pkl")

from google.colab import files
files.download("model.pkl")